[program:dbus]
command=/usr/bin/dbus-daemon --system --nofork --nopidfile
user=root
autostart=true
autorestart=true
startsecs=1
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/dbus.log
stderr_logfile=/var/log/dbus.err
